services:
  node:
    container_name: node
    image: node
    build:
      context: ./node
      args:
        SSL_KEY_PATH: ${SSL_KEY_PATH}
        SSL_CERT_PATH: ${SSL_CERT_PATH}
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - sqlite_data:$DB_DIR
    networks:
      - transcendance
    restart: always

volumes:
  sqlite_data:

networks:
  transcendance:
    name: transcendance
    driver: bridge
