services:
  node:
    build: ./node
    container_name: node
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - sqlite_data:$DB_DIR
    networks:
      - transcendance

volumes:
  sqlite_data:

networks:
  transcendance:
    name: transcendance
    driver: bridge
